"""empty message

Revision ID: 906eb2cf52fc
Revises: 7aa8e1f12d8f
Create Date: 2021-09-05 12:15:31.069285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906eb2cf52fc'
down_revision = '7aa8e1f12d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('artists', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'seeking_venue')
    # ### end Alembic commands ###
