"""empty message

Revision ID: 09e8ef7e7c77
Revises: d26e1193bec8
Create Date: 2022-01-22 18:46:44.542216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e8ef7e7c77'
down_revision = 'd26e1193bec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('movies_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'actors', 'movies', ['movies_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actors', type_='foreignkey')
    op.drop_column('actors', 'movies_id')
    # ### end Alembic commands ###
