"""empty message

Revision ID: 80113ee731a4
Revises: 09e8ef7e7c77
Create Date: 2022-01-22 19:36:51.197552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80113ee731a4'
down_revision = '09e8ef7e7c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'movies_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'movies_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
